### ISSUE TITLE
Remove Assert and other files from Repository Root

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xActiveDirectory#144] opened 2017-02-22 07:09 UTC
The files appear to be some sort of legacy tests, but the purpose is not documented and they are not executed by any automation. They should be removed to avoid confusion - or at least moved to a subfolder.

The files are:
- Assert-HADC.ps1
- Assert-ParentChildDomains.ps1
- HADCConfiguration.psd1
- ParentChildConfig.psd1
- xActiveDirectory_TechNetDocumentation.html
- Misc/New-ADDomainTrust.ps1

If acceptable I will submit a PR to remove them.

**Comment by johlju** [comment] 2018-05-08 07:59
This seems to be a duplicate of issue #104. Keeping this open, and closing #104. Please see https://github.com/PowerShell/xActiveDirectory/issues/104#issuecomment-240820871.

**Closed** 2019-06-18 11:19 UTC
Labels: enhancement, help wanted
