### ISSUE TITLE
Duplication of code in example in readme.md

### ISSUE THREAD

**Issue by AspenForester** [PowerShell/xActiveDirectory#198] opened 2018-06-01 16:36 UTC
In the first example, asserting a highly available domain, the entire block of code intended for the example has been pasted in twice.

**Comment by AspenForester** [comment] 2018-06-01 16:39
Likewise, the code for configuration AssertParentChildDomains shows up again at the end of the next example.

**Comment by johlju** [comment] 2018-06-04 12:01
Label this as help wanted so that anyone in the community can run with this.

**Comment by johlju** [comment] 2018-06-12 08:49
Re-opening this as there is still a duplicate of AssertParentChildDomains.

**Comment by thequietman44** [comment] 2018-06-12 13:18
I created a new pull request with the duplicate AssertParentChildDomains removed.

**Closed** 2018-06-13 19:20 UTC
Labels: documentation, good first issue, in progress
